### ISSUE TITLE
Bot not relaying messages in discord

### ISSUE THREAD

**Issue by 84100** [FragLand/terracord#14] opened 2020-01-01 16:15 UTC
Hi

I understand this probably isn't the best place to ask for help, but I have tried to get this working and not sure where I'm going wrong anymore (spent so much time trying to get this working! :D). I have built the terracord.dll and put all the bot info (bot token and channel ID) in to the xml config file. I can see terracord executing messages in the Terraria server console, however Discord doesn't seem to be communicating with Terraria (I have a bot but it is not executing any messages). I would really, really appreciate your help with this, thanks.

**Comment by ldilley** [comment] 2020-01-01 16:45
Greetings, @84100.

Requesting support via GitHub issues is perfectly acceptable. Do you actually see your bot user within the Discord server come online after TShock starts or does the bot user appear offline? If offline, then it is not connecting. In that case, I would check `terracord.xml` to ensure that your bot token is correct. This should not be confused with the application's client ID or client secret.

If the Discord bot is coming online and does not receive or send messages in a designated channel, I would validate the channel ID. If the channel ID is indeed correct in your config, then you should review the bot permissions on the Discord side to confirm it is able to read and send messages under text permissions.

Are any exceptions printed out to the TShock console by chance? If so, please paste them in a reply to this issue.

Just for awareness, we have a working Terracord bot named Drippler on https://discord.frag.land/ using the latest commit. 

I plan on implementing logging today per #7. So, if you are still experiencing this symptom after rebuilding the future commit with log support, perhaps we will be able to determine a root cause using the logs.

Lastly, I apologize for the trouble you are experiencing. Once we achieve the 1.0.0 milestone, a release zip archive will be published containing the necessary DLLs and a configuration template. This should make things easier on users since they will not be required to build the Terracord plugin on their own. If you have any suggestions to make the building, configuring, or troubleshooting process easier, we are open to any feedback that you may have to share.

**Comment by 84100** [comment] 2020-01-01 17:21
@ldilley thank you!

So, the bot user is in the server but offline. I have checked the token over and over, it is correct and I'm able to connect the bot and get it online using a different script.

I do get -

"Terracord" has had an unhandled exception thrown by one of its ServerLeave handlers:
System.NullReferenceException: Object reference not set to an instance of an object.
    at Terracord.Terracord.OnLeave(LeaveEventArgs args)
    at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args)

Just to make sure I'm not doing something very silly, the terracord.xml is to be placed in the same location as other configs (same destination as tshock.sqlite)? The files needed are the terracord.dll, terracord.xml and dependencies listed in the readme? 

I'm honestly really pleased you got back so fast, I've been trying to get this running since yesterday and I feel like it's so close!

**Comment by 84100** [comment] 2020-01-01 18:10
Do you think this is something I'm doing wrong, or does the exception give you any info?

I'm positive that the bot token is correct, but it doesn't come online when starting up the server.

Sorry to bother you with this, let me know if it's easier for me to wait for 1.0.0.

**Comment by ldilley** [comment] 2020-01-01 18:20
You are welcome.

That particular exception is unrelated and can be ignored. It will be fixed per #11.

`terracord.xml` should indeed reside under the `tshock` sub-directory (relative to a top-level directory where `TerrariaServer.exe` exists). The path for the XML config should contain `tshock.sqlite` like you mentioned along with `config.json`, `motd.txt`, `rules.txt`, etc. If `Terracord.dll` was unable to open `terracord.xml`, `TerrariaServer.exe` should abort with `FileNotFoundException`.

Can you double check that your instance of `terracord.xml` has all element tags properly closed and that all attributes are between double quotes? If you do not mind recompiling the DLL, you could uncomment line 71 of commit a8775e5 which contains:

```csharp
Console.WriteLine($"{botToken} {channelId} {commandPrefix} {botGame} {broadcastColor[0]} {broadcastColor[1]} {broadcastColor[2]}");
```

This should spit out all the options at runtime if you do not mind having the token displayed. Could you also please attach/paste a copy of your sanitized (without the bot token and channel ID) `terracord.xml`?

I've attached a screenshot of my `ServerPlugins` directory contents below. I hope that helps.

![TShock_ServerPlugins_screenshot](https://user-images.githubusercontent.com/3323717/71644615-5c659100-2c99-11ea-9d59-110e715e285e.png)

**Comment by 84100** [comment] 2020-01-01 20:54
Okay so I un-commented line 71, its showing my bot token and channel ID in the console and I'm positive the .dll and config file are in the right location.

![1](https://user-images.githubusercontent.com/25401910/71646004-707cb300-2cd8-11ea-8f0b-b496fd6586d6.png)

![2](https://user-images.githubusercontent.com/25401910/71646006-76729400-2cd8-11ea-9d8a-123c45add537.png)

Any ideas?

![3](https://user-images.githubusercontent.com/25401910/71646733-6a400400-2ce3-11ea-936a-7fe218e82372.PNG)

![4](https://user-images.githubusercontent.com/25401910/71646735-6dd38b00-2ce3-11ea-9979-dd00c65fabea.PNG)

**Comment by ldilley** [comment] 2020-01-01 23:11
Your XML syntax appears fine. In regards to your last screenshot, do you also have the following DLLs in the `ServerPlugins` directory?

`Discord.Net.Core.dll`
`Discord.Net.Rest.dll`
`Discord.Net.WebSocket.dll`
`Newtonsoft.Json.dll`

I do not see the files referenced above in the screenshot you attached (unless the image got truncated).

By the way, logging is now supported in the latest commit at the time of this writing, c104866. If you rebuild and load the plugin using this latest source, a `terracord.log` file should appear under your `tshock` directory where the `terracord.xml` file resides. Similar output contained in the log file should also get displayed within the TShock console. This should help us diagnose your problem. Below is an example log excerpt of what a successful run should look like. The gateway status change entries will require that the Discord.Net DLLs be present in the `ServerPlugins` directory of course.

```
[1/1/2020 3:12:35 PM] Server has started.
[1/1/2020 3:13:03 PM] Connecting to Discord...
[1/1/2020 3:13:03 PM] 15:13:03 Discord     Discord.Net v2.1.1 (API v6)
[1/1/2020 3:13:03 PM] 15:13:03 Gateway     Connecting
[1/1/2020 3:13:04 PM] 15:13:04 Gateway     Connected
[1/1/2020 3:13:04 PM] 15:13:04 Gateway     Ready
[1/1/2020 3:16:00 PM] <Maldemort@Discord> test
[1/1/2020 3:20:47 PM] Melinda has joined the server.
[1/1/2020 3:21:00 PM] Melinda said: Slimes!
[1/1/2020 3:21:25 PM] Melinda has left the server.
[1/1/2020 3:22:11 PM] Server is shutting down.
[1/1/2020 3:22:11 PM] 15:22:11 Gateway     Disconnecting
```

**Comment by 84100** [comment] 2020-01-02 00:54
Edit - Made a mistake, I didn't update the config for the latest commit you just referred me to.

However I still don't have an online bot in the Discord. Here is the log:

[1/2/2020 1:11:03 AM] terracord.xml parsed.
[1/2/2020 1:11:03 AM] Server has started.
[1/2/2020 1:11:24 AM] Connecting to Discord...
[1/2/2020 1:11:24 AM] 01:11:24 Discord     Discord.Net v2.1.1 (API v6)
[02/01/2020 01:11:25] MechanicBunny has joined the server.
[02/01/2020 01:11:29] B4100 has joined the server.

I have the Discord.Net DLLs in the ServerPlugin directory, do you know why the Gateway does not show in my logs?

![5](https://user-images.githubusercontent.com/25401910/71648410-c878e100-2cfb-11ea-9d83-dd5e9b79eb0d.PNG)

**Comment by ldilley** [comment] 2020-01-02 01:20
Did you add the new option for chat logging to your `terracord.xml`? The end of your config file should look like this now:

```xml
  <!-- Terraria broadcast color in RGB -->
  <broadcast red="255" green="215" blue="0" />
  <!-- Log all chat messages -->
  <log chat="true" />
</configuration>
```

I suspect that the lack of this small item may be causing the nasty-looking stack trace you included in your reply. Once #10 is implemented, the output should appear more friendly. :wink:

**Comment by ldilley** [comment] 2020-01-02 01:35
I just saw your modified reply. No worries -- I should have informed you about the config change as well.

The lack of gateway messages is odd. What are you using for .NET runtime and what version? This seems to be an issue with Discord.Net and/or your .NET runtime. Perhaps the two are not playing well together.

For reference, I am using Discord.Net 2.1.1 under both Debian 10 and Windows Server 2019. I am also using the latest release of TShock, 4.3.26, on both platforms. Lastly, I am using .NET Core SDK 3.1.100 under Linux and .NET Framework 4.7 on the Windows Server 2019 system.

**Comment by ldilley** [comment] 2020-01-02 03:00
I am going to make another commit which will allow users to increase the verbosity of the Discord.Net logs at runtime. This will require adding 1 more option to `terracord.xml`. I'll reply to this issue after the commit.

**Comment by ldilley** [comment] 2020-01-02 03:52
PR #17 has been merged. Just append the new debug mode lines to your copy of `terracord.xml` and set the value to `true`. The tail of your config should now look like below:

```xml
  <!-- Log all chat messages -->
  <log chat="true" />
  <!-- Debug mode -->
  <debug mode="true" />
</configuration>
```

You should now (hopefully) get more verbose output similar to mine below:

```
[1/1/2020 9:27:51 PM] terracord.xml parsed.
[1/1/2020 9:27:52 PM] Server has started.
[1/1/2020 9:28:06 PM] Connecting to Discord...
[1/1/2020 9:28:07 PM] 21:28:07 Discord     Discord.Net v2.1.1 (API v6)
[1/1/2020 9:28:07 PM] 21:28:07 Rest        GET voice/regions: 119.96 ms
[1/1/2020 9:28:07 PM] 21:28:07 Rest        GET users/@me: 59.99 ms
[1/1/2020 9:28:07 PM] 21:28:07 Gateway     Connecting
[1/1/2020 9:28:07 PM] 21:28:07 Gateway     Connecting ApiClient
[1/1/2020 9:28:07 PM] 21:28:07 Rest        GET gateway: 8.4 ms
[1/1/2020 9:28:07 PM] 21:28:07 Gateway     Identifying
[1/1/2020 9:28:07 PM] 21:28:07 Gateway     Sent Identify
[1/1/2020 9:28:07 PM] 21:28:07 Gateway     Received Hello
[1/1/2020 9:28:07 PM] 21:28:07 Gateway     Heartbeat Started
[1/1/2020 9:28:07 PM] 21:28:07 Gateway     Sent Heartbeat
[1/1/2020 9:28:08 PM] 21:28:08 Gateway     Received Dispatch (READY)
[1/1/2020 9:28:08 PM] 21:28:08 Gateway     GuildDownloader Started
[1/1/2020 9:28:08 PM] 21:28:08 Gateway     Sending Status
[1/1/2020 9:28:08 PM] 21:28:08 Gateway     Sent StatusUpdate
[1/1/2020 9:28:08 PM] 21:28:08 Gateway     Connected
[1/1/2020 9:28:08 PM] 21:28:08 Gateway     Raising Event
[1/1/2020 9:28:08 PM] 21:28:08 Gateway     Received Dispatch (GUILD_AVAILABLE)
[1/1/2020 9:28:08 PM] 21:28:08 Gateway     Connected to Frag Land
[1/1/2020 9:28:08 PM] 21:28:08 Gateway     Received HeartbeatAck
[1/1/2020 9:28:08 PM] 21:28:08 Gateway     Latency = 265 ms
[1/1/2020 9:28:08 PM] 21:28:08 Gateway     GuildDownloader Stopped
[1/1/2020 9:28:08 PM] 21:28:08 Gateway     Received Dispatch (PRESENCE_UPDATE)
[1/1/2020 9:28:08 PM] 21:28:08 Gateway     Received Dispatch (MESSAGE_CREATE)
[1/1/2020 9:28:08 PM] 21:28:08 Rest        POST channels/<channel_ID>/messages: 91.7 ms
[1/1/2020 9:28:08 PM] 21:28:08 Gateway     Ready
[1/1/2020 9:28:17 PM] 21:28:17 Gateway     Received Dispatch (PRESENCE_UPDATE)
[1/1/2020 9:28:32 PM] 21:28:32 Gateway     Received Dispatch (PRESENCE_UPDATE)
[1/1/2020 9:28:47 PM] 21:28:47 Gateway     Received Dispatch (PRESENCE_UPDATE)
[1/1/2020 9:28:49 PM] 21:28:49 Gateway     Sent Heartbeat
[1/1/2020 9:28:49 PM] 21:28:49 Gateway     Received HeartbeatAck
[1/1/2020 9:28:49 PM] 21:28:49 Gateway     Latency = 47 ms
[1/1/2020 9:28:52 PM] 21:28:52 Gateway     Received Dispatch (PRESENCE_UPDATE)
[1/1/2020 9:29:02 PM] 21:29:02 Gateway     Received Dispatch (PRESENCE_UPDATE)
[1/1/2020 9:29:03 PM] Server is shutting down.
[1/1/2020 9:29:03 PM] 21:29:03 Gateway     Heartbeat Stopped
[1/1/2020 9:29:03 PM] 21:29:03 Gateway     Disconnecting
[1/1/2020 9:29:03 PM] 21:29:03 Gateway     Disconnecting ApiClient
[1/1/2020 9:29:03 PM] 21:29:03 Rest        POST channels/<channel_ID>/messages: 105.25 ms
```

I hope this helps to shed some more light on the issue. I need to step away for the day, but should be available again in ~19 hours.

**Comment by 84100** [comment] 2020-01-02 12:59
> The lack of gateway messages is odd. What are you using for .NET runtime and what version? This seems to be an issue with Discord.Net and/or your .NET runtime. Perhaps the two are not playing well together.
> 
> For reference, I am using Discord.Net 2.1.1 under both Debian 10 and Windows Server 2019. I am also using the latest release of TShock, 4.3.26, on both platforms. Lastly, I am using .NET Core SDK 3.1.100 under Linux and .NET Framework 4.7 on the Windows Server 2019 system.

My server is a small community hosted from a home PC, so please excuse me if I do not follow all the language used as I'm an amateur!

I'm using Discord.Net v2.1.1 on Windows 10 Home using the latest 4.3.26 TShock release and .NET Framework 4.8. 

Tested the latest, this is the log:

```
[1/2/2020 12:46:43 PM] terracord.xml parsed.
[1/2/2020 12:46:43 PM] Server has started.
[1/2/2020 12:46:59 PM] Connecting to Discord...
[1/2/2020 12:46:59 PM] 12:46:59 Discord     Discord.Net v2.1.1 (API v6)
[02/01/2020 12:46:59] 12:46:59 Rest        GET voice/regions: 323.89 ms
[02/01/2020 12:46:59] 12:46:59 Rest        GET users/@me: 139.81 ms
[02/01/2020 12:47:51] B4100 has joined the server.
[02/01/2020 12:47:54] B4100 said: test
[02/01/2020 12:47:58] B4100 said: !hey
[02/01/2020 12:48:06] B4100 has left the server.
```

Let me know , thanks again for all the help.

**Comment by kyleighd** [comment] 2020-01-02 19:46
I don't see Newtonsoft.Json.dll, and Discord.Net.Core depends on that, is it there?
https://www.nuget.org/packages/Discord.Net.Core/

**Comment by 84100** [comment] 2020-01-02 21:15
Yes Newtonsoft.Json.dll is there in the ServerPlugin directory.

**Comment by ldilley** [comment] 2020-01-02 22:51
No problem at all, @84100. Your OS and versions of Discord.Net, .NET Framework, and TShock all appear fine. Execution is obviously making it to the `BotConnect()` method since the log level is getting set. The program seems to be getting hung up on `DiscordSocketClient.LoginAsync()` or `DiscordSocketClient.StartAsync()`. I am not certain why.

As an aside, I am wondering why your timestamp format seems to change. That also seems to coincide with when Discord fails to complete a connection. In other words, your log messages contain a timestamp of the form `[1/2/2020 12:46:59 PM]` and then it changes to `[02/01/2020 12:46:59]` with the initial REST message. I do not see this behavior in my output.

Would it be possible for you to build and run the sample ping bot program from the Discord.Net repo at https://github.com/discord-net/Discord.Net/blob/dev/samples/01_basic_ping_bot/Program.cs? If the behavior is the same, we can at least rule out TShock and Terracord.

**Comment by 84100** [comment] 2020-01-03 13:14
So I made a ping bot and it is working great. 

I did also notice the timestamps being displayed in both US and UK style, but was unsure why and if that could be the root cause.

![bot](https://user-images.githubusercontent.com/25401910/71725105-b3e73680-2e2a-11ea-8a7d-1f182df8559d.PNG)

**Comment by ldilley** [comment] 2020-01-03 23:47
Thank you for testing that, @84100. I've merged some changes that will _hopefully_ resolve your issue. I believe it was a sequencing problem with asynchronous versus synchronous code. The timestamp issue should also be cleared up now. The latest commit, 3d0b827, is available for your testing pleasure. :)

**Comment by 84100** [comment] 2020-01-04 02:21
Still no joy I'm afraid.

The log:

```
[01/04/2020 01:53:40 +00:00] Server has started.
[01/04/2020 01:53:51 +00:00] terracord.xml parsed.
[01/04/2020 01:53:51 +00:00] Configuration Values
--------------------
[01/04/2020 01:53:51 +00:00] Bot Token: 0000000000000000000000000000000000000000000
[01/04/2020 01:53:51 +00:00] Channel ID: 0000000000000000000
[01/04/2020 01:53:51 +00:00] Command Prefix: !
[01/04/2020 01:53:51 +00:00] Bot Game: Terraria
[01/04/2020 01:53:51 +00:00] Broadcast Color (RGB): 255, 215, 0
[01/04/2020 01:53:51 +00:00] Log Chat: True
[01/04/2020 01:53:51 +00:00] Debug Mode: True
[01/04/2020 01:53:51 +00:00] Connecting to Discord...
[01/04/2020 01:53:51 +00:00] 01:53:51 Discord     Discord.Net v2.1.1 (API v6)
[01/04/2020 01:53:51 +00:00] 01:53:51 Rest        GET voice/regions: 308.13 ms
[01/04/2020 01:53:52 +00:00] 01:53:52 Rest        GET users/@me: 149.18 ms
[01/04/2020 01:53:52 +00:00] Adam The Great has joined the server.
[01/04/2020 01:53:55 +00:00] Mat has joined the server.
[01/04/2020 01:53:57 +00:00] Kz13 has joined the server.
[01/04/2020 01:54:24 +00:00] Aetheraxia has joined the server.
[01/04/2020 01:54:33 +00:00] Adam The Great said: testing
[01/04/2020 01:54:39 +00:00] Kz13 said: Ok
[01/04/2020 01:54:48 +00:00] B4100 has joined the server.
```

I'm getting this error in the console, but not the log:

```
[Server API] Warning Plugin "Terracord" has had an unhandled exception thrown by one of its GamePostInitialize handlers:
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'Discord.Optional`1[System.String]'. Path 'email', line 1, position 149. ---> System.ArgumentException: Could not cast or convert from {null} to Discord.Optional`1[System.String].
   at Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(Object value, Type initialType, Type targetType)
   at Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(Object initialValue, CultureInfo culture, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Discord.API.DiscordRestApiClient.DeserializeJson[T](Stream jsonStream)
   at Discord.API.DiscordRestApiClient.<SendAsync>d__59`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.API.DiscordRestApiClient.<GetMyUserAsync>d__140.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.DiscordRestClient.<OnLoginAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.WebSocket.DiscordSocketClient.<OnLoginAsync>d__94.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Discord.Rest.BaseDiscordClient.<LoginInternalAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Discord.Rest.BaseDiscordClient.<LoginAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Terracord.Terracord.<BotConnect>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Terracord.Terracord.OnPostInitialize(EventArgs args)
   at TerrariaApi.Server.HandlerCollection`1.Invoke(ArgsType args)
```

**Comment by ldilley** [comment] 2020-01-04 02:52
A clue! Check https://github.com/Makar8000/ACT-Discord-Triggers/issues/48. Similar behavior results from using an older version of `Newtonsoft.Json.dll`. Below is a screenshot of my versions. The one in my `ServerPlugins` directory is the newer and larger-sized DLL targeting .NET Standard 2.0. The details on the left are for the older DLL which resides one directory up (with `TerrariaServer.exe`). See if you can fetch a newer `Newtonsoft.Json.dll`, copy it to the `ServerPlugins` directory, and reload/restart.

![Newtonsoft Json dll_versions](https://user-images.githubusercontent.com/3323717/71758818-87efa380-2e72-11ea-91a6-835592cf99f1.png)

**Comment by 84100** [comment] 2020-01-04 03:06
Yes! It works :D 

Thanks so much for your patience, I hope I didn't cause you to do too much work over my old `Newtonsoft.Json.dll` version. If I can help in any way, let me know!

**Comment by ldilley** [comment] 2020-01-04 03:21
Fantastic! You are very welcome. We solved the mystery of the morphing timestamp at least. The async/sync changes and restructuring were probably a good idea to implement anyhow. I sincerely appreciate the prompt communication along with your time and effort for the multiple rounds of updating and rebuilding.

I'll go ahead and close this issue. Feel free to submit a new one if something else comes up. You also know where to find me.

**Closed as completed by ldilley** 2020-01-04 03:21 UTC
Labels: bug, question
